-module(nm_cleanup).

-export([start/0, clean_up/0]).


%%
%% API Functions
%%

start() ->
	do().


%%
%% Local Functions
%%

do() ->
	timer:apply_after(600000, ?MODULE, clean_up, []), % in milliseconds, 600000 = 10 min
	ok.


clean_up() ->
	% cleanup old user session
    model_session:clear_old(129600), % in seconds, 129600 = 36 hours

	% TODO: cleanup .png image generated by rrdtool

    do().